packages/trader/src/Utils/Validator/validator.ts

maryia/chore: validator type improvements

---

packages/trader/src/Modules/Trading/Components/Elements/payout-per-point-mobile.tsx
packages/trader/src/Modules/Trading/Components/Elements/purchase-button.jsx
packages/trader/src/Modules/Trading/Components/Elements/purchase-fieldset.jsx
packages/trader/src/Modules/Trading/Components/Form/Purchase/cancel-deal-info.tsx
packages/trader/src/Modules/Trading/Components/Form/Purchase/contract-info.tsx
packages/trader/src/Modules/Trading/Components/Form/Purchase/value-movement.tsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/barrier.tsx
packages/trader/src/Types/common-prop.type.ts

- Refactor: `<ValueMovement />` was moved to a separate file.
- TS migration of `cancel-deal-info.jsx`, `contract-info.jsx` and `value-movement.jsx` files

Kate / DTRA-354 / Components/Form/Purchase files in Trader package

---

package-lock.json
packages/components/src/components/contract-card/contract-card-items/contract-card-header.tsx
packages/components/src/components/contract-card/contract-card-items/contract-type-cell.tsx
packages/shared/package.json
packages/shared/src/utils/contract/__tests__/contract.spec.ts
packages/shared/src/utils/contract/contract.ts
packages/shared/src/utils/contract/contract.tsx

- removed localize from contract-card-header.tsx

Maryia/dtra-373/remove localize from ContractCardHeader component

---

packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/info.tsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/widgets.jsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/amount.tsx
packages/trader/src/Modules/Trading/Containers/Multiplier/multiplier-amount-modal.tsx
packages/trader/src/Modules/Trading/Containers/Multiplier/multiplier-options.tsx

- TS migration
- Removed codesmells (//TODO)

Kate / DTRA-386 / TS migration: MultipliersInfo in Trader package

---

packages/trader/src/App/Components/Form/TimePicker/dialog.tsx

Maryia/fix: sonarcloud issues

---

packages/trader/src/Modules/Trading/Components/Elements/purchase-button.tsx
packages/trader/src/Modules/Trading/Components/Elements/purchase-fieldset.tsx
packages/trader/src/Modules/Trading/Containers/purchase.tsx
packages/trader/src/Stores/Modules/SmartChart/chart-barrier-store.ts
packages/trader/src/Stores/Modules/Trading/Actions/purchase.ts
packages/trader/src/Stores/Modules/Trading/Actions/start-date.ts
packages/trader/src/Stores/Modules/Trading/Constants/validation-rules.ts
packages/trader/src/Stores/Modules/Trading/Helpers/allow-equals.ts
packages/trader/src/Stores/Modules/Trading/Helpers/limit-orders.ts
packages/trader/src/Stores/Modules/Trading/Helpers/logic.ts
packages/trader/src/Stores/Modules/Trading/Helpers/proposal.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts
packages/trader/src/Stores/useTraderStores.tsx
packages/trader/src/Types/common-prop.type.ts

- fix: build errors in Package 4 cause by TS issues

Maryia/fix: build errors in Package 4 cause by TS issues

---

packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/cancel-deal.tsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration-modal.tsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/expiration.tsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/Multiplier/widgets.tsx

Replace localizes with Localizes in Multiplier components if Localize components are expected by children

Maryia/Replace localizes with Localizes in Multiplier components

---

packages/trader/src/App/Components/Routes/helpers.ts
packages/trader/src/App/Components/Routes/route-with-sub-routes.tsx
packages/trader/src/App/Containers/Routes/routes.tsx
packages/trader/src/Assets/Trading/Categories/Description/accumulator-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/asian-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/call-put-spread-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/end-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/even-odd-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/high-low-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/lb-call-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/lb-high-low-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/lb-put-trade-desciption.tsx
packages/trader/src/Assets/Trading/Categories/Description/match-diff-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/multiplier-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/over-under-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/reset-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/rise-fall-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/run-high-low-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/stay-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/tick-high-low-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/touch-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/turbos-trade-description.tsx
packages/trader/src/Assets/Trading/Categories/Description/vanilla-trade-description.tsx
packages/trader/src/Modules/Trading/Containers/Multiplier/multiplier-amount-modal.tsx
packages/trader/src/Modules/Trading/Containers/Multiplier/multiplier-options.tsx
packages/trader/src/Modules/Trading/Containers/chart-widgets.tsx
packages/trader/src/Stores/Modules/Trading/Helpers/preview-proposal.ts

- Refactor: remove some code smells

Kate/ fix: code smells

---

packages/trader/src/Modules/SmartChart/index.tsx

- to fix types in SmartChart index

Maryia/TS-7/fix: types in SmartChart index

---

packages/trader/src/AppV2/Components/BottomNav/bottom-nav.tsx
packages/trader/src/AppV2/Components/EmptyMessage/__tests__/empty-message.spec.tsx
packages/trader/src/AppV2/Components/EmptyMessage/empty-message.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Containers/Positions/positions.tsx
packages/trader/src/AppV2/app.tsx

- to add redirect functionality to the button inside EmptyMessage component
- to add tests

Maryia/Positions-redesign/improve EmptyMessage component + add tests

---

packages/trader/src/App/app.tsx
packages/trader/src/AppV2/Containers/Positions/positions.tsx
packages/trader/src/AppV2/Hooks/useClosedPositions.ts
packages/trader/src/AppV2/app.tsx
packages/trader/src/Stores/Modules/Positions/positions-store.ts
packages/trader/src/Stores/Modules/Trading/__tests__/trade-store.spec.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts
packages/trader/src/Stores/Modules/index.js
packages/trader/src/Stores/Modules/index.ts
packages/trader/src/Stores/Providers/modules-providers.tsx
packages/trader/src/Stores/base-store.ts
packages/trader/src/Stores/useModulesStores.tsx
packages/trader/src/Types/common-prop.type.ts

Add modules store  and useclosedposition hook

Add modules store  and useclosedposition hook

---

packages/trader/src/AppV2/Components/Filter/filter.scss
packages/trader/src/AppV2/Components/Filter/filter.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Containers/Positions/positions.tsx

- Remove some TODOs and some parts of css as it's not need anymore after Quill library updates
- Add new props
- Refactor functions in Filter component

DTRA-1279 / Kate / Refactor: update filter component based on Quill UI library changes

---

packages/trader/src/AppV2/Components/Filter/filter.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Containers/Positions/positions.scss
packages/trader/src/AppV2/Containers/Positions/positions.tsx
packages/trader/src/AppV2/Hooks/useClosedPositions.ts
packages/trader/src/AppV2/Utils/positions-utils.ts

Please provide a summary of the change.

DTRA-1279 / Kate / Use hook for real data

---

packages/trader/src/AppV2/Components/EmptyMessage/__tests__/empty-message.spec.tsx
packages/trader/src/AppV2/Components/EmptyMessage/empty-message.scss
packages/trader/src/AppV2/Components/EmptyMessage/empty-message.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Containers/Positions/positions.tsx
packages/trader/src/AppV2/app.tsx

- Replace icons, removed unused button and its functionality
- Refactored CSS
- Refactored tests

DTRA-1279 / Kate / Refactor: add new content for empty page

---

packages/core/package.json
packages/trader/package.json

Please provide a summary of the change.

DTRA-1279 / Kate / Chore: update quill version

---

packages/trader/src/AppV2/Components/DatePicker/date-picker.tsx
packages/trader/src/AppV2/Components/Filter/custom-time-filter-button.tsx
packages/trader/src/AppV2/Components/Filter/time-filter.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Hooks/useTimeFilter.ts
packages/trader/src/AppV2/Hooks/useTradeTypeFilter.ts
packages/trader/src/Stores/Modules/Positions/positions-store.ts

DTRA-1279 / Kate/ Add filtration hooks 

---

packages/trader/src/AppV2/Components/DatePicker/date-picker.scss
packages/trader/src/AppV2/Components/DatePicker/date-picker.tsx
packages/trader/src/AppV2/Components/Filter/__tests__/time-filter.spec.tsx
packages/trader/src/AppV2/Components/Filter/contract-type-filter.tsx
packages/trader/src/AppV2/Components/Filter/custom-time-filter-button.tsx
packages/trader/src/AppV2/Components/Filter/time-filter.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx

- Rework time filtration for Today and Yesterday
- Fix double-filter problem
- Changed css after design confirmation
- Add preventing user from closing future date
- Sort props

DTRA-1279 / Kate / Double filtration and extra filter options

---

packages/trader/src/AppV2/Components/ContractCard/__tests__/contract-cards-sections.spec.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-card-list.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-card-status-timer.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-card.scss
packages/trader/src/AppV2/Components/ContractCard/contract-card.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-cards-sections.tsx
packages/trader/src/AppV2/Components/ContractCard/index.ts
packages/trader/src/AppV2/Components/DatePicker/date-picker.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Containers/Positions/positions.scss
packages/trader/src/AppV2/Utils/__tests__/positions-utils.spec.ts
packages/trader/src/AppV2/Utils/positions-utils.ts

- Add Contract Card Date separator component + tests
- Create function helper for date formatting + tests
- Change style according to figma scrolling behavior

DTRA-1279 / Kate / Add section separator 

---

packages/stores/src/mockStore.ts
packages/trader/src/AppV2/Components/Filter/__tests__/time-filter.spec.tsx
packages/trader/src/AppV2/Components/Filter/contract-type-filter.tsx
packages/trader/src/AppV2/Components/Filter/time-filter.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx
packages/trader/src/AppV2/Hooks/__tests__/useTimeFilter.spec.tsx
packages/trader/src/AppV2/Hooks/__tests__/useTradeTypeFilter.spec.tsx
packages/trader/src/AppV2/Utils/positions-utils.ts

Tests + removing sonarcloud issues

DTRA-1279 / Kate / Tech Debt

---

packages/trader/src/AppV2/Components/ContractCard/__tests__/contract-cards-sections.spec.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-cards-sections.tsx
packages/trader/src/AppV2/Containers/Positions/positions-content.tsx

- finilise Infinite scroll in Closed positions
- fix loading state for Closed positions

Maryia/position-redesign/Infinite scroll + loading state for Closed positions

---

packages/trader/package.json
packages/trader/src/AppV2/Components/ContractCard/__tests__/contract-card-list.spec.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-card-list.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-card.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-cards-sections.tsx
packages/trader/src/AppV2/Components/Filter/__tests__/contract-type-filter.spec.tsx
packages/trader/src/AppV2/Components/Filter/__tests__/time-filter.spec.tsx
packages/trader/src/AppV2/Components/TotalProfitLoss/total-profit-loss.tsx

- fix failing tests
- address sonarcloud issues 
- use clsx instead of classnames

Maryia/positions-redesign/fix: tests + address sonarcloud + use clsx

---

packages/trader/src/AppV2/Components/BottomNav/__tests__/bottom-nav.spec.tsx
packages/trader/src/AppV2/Components/BottomNav/bottom-nav.tsx

- to display correct active positions count n the Footer

Maryia/positions-redesign/feat: display correct active positions count

---

packages/trader/src/AppV2/Components/BottomNav/bottom-nav.tsx

- to fix positions count to hide the count in the Footer when there are no open positions

Maryia/positions-redesign/fix: positions count in Footer

---

packages/trader/src/AppV2/Components/DatePicker/__tests__/date-picker.spec.tsx
packages/trader/src/AppV2/Components/DatePicker/date-picker.tsx

- Support a single date selection

DTRA-1279 / Kate / Add a single date selection
